name: Development

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  test:
    uses: open-sauced/hot/.github/workflows/development.yml@main
  build:
    runs-on: ubuntu-latest
    steps: 
        - name: "📦 run build"
          run: npm run build
